### ISSUE TITLE
[Bug] Discord button is not visibile in dark mode

### ISSUE THREAD

**Issue by Mayank-Sharma17** [techhub-community/Hackbook#135]
![Screenshot 2023-10-13 000200](https://github.com/techhub-community/Hackbook/assets/113251342/a0caf458-1931-48b4-880f-3c0847974cce)

expected:
![Screenshot 2023-10-13 000817](https://github.com/techhub-community/Hackbook/assets/113251342/b4807251-d73f-4a33-a1b7-9dae66f19b43)

**Comment by ashish-gopalika** [comment]
@Mayank-Sharma17 You have found a valid bug. You are assigned for it and now you can make a PR with the proper solution.

**Comment by ashish-gopalika** [comment]
@raghavendrashande Great that you showed enthusiasm for solving the bug. But it's a standard practice of open source that before making any PR related to any issue, ask the maintainers to assign you to that particular issue. And those who are assigned should only work on that particular issue, always the preference is given on the first come basis.

So here if @Mayank-Sharma17  doesn't make a valid PR in 2 days then only your PR for this issue will be considered valid.

**Comment by raghavendrashande** [comment]
@ashish-gopalika Yes sir!! Will keep that in mind. Thank you!!😊

**Comment by Mayank-Sharma17** [comment]
@ashish-gopalika can you please add hacktoberfest label :)
